### ISSUE TITLE
/opt/cmd.sh: line 59: conditional binary operator expected

### ISSUE THREAD

**Issue by bhattvishal** [suculent/platformio-docker-build#2]
I keep getting issue 

> (conditional binary operator expected) on line 59 in cmd.sh file

with exit code 2 on Ubuntu 1604

![error](https://user-images.githubusercontent.com/4817681/60665951-786fad80-9e83-11e9-84c3-ba0acf50f224.PNG)

**Comment by exocode** [comment]
same here

**Comment by suculent** [comment]
Ok, I am trying to fix it... once tests will pass on codefresh.io I’ll be back.

**Comment by suculent** [comment]
Fixed, closing. Thanks for report, sorry for slow speed.

**Comment by 2114L3** [comment]
still getting this error. 
please update your latest flag on docker hub as you are still pointing to `c9e3dacc238397bb59796beedc531a48a73cd92858cd02327fc4f86a5861aac8` a year old
